/* Generated by scripts/generate-api-schema.py; DO NOT EDIT. */
#ifndef COREX_GENERATED_API_SCHEMA_H
#define COREX_GENERATED_API_SCHEMA_H
#include <stddef.h>
#include <stdint.h>
#include "corex_protocol.h"
typedef enum {
    COREX_WIRE_U32 = 1,
    COREX_WIRE_I32 = 2,
    COREX_WIRE_U64 = 3,
    COREX_WIRE_I64 = 4,
    COREX_WIRE_SIZE_U64 = 5,
    COREX_WIRE_BOOL_U32 = 6,
    COREX_WIRE_ALLOCATION_ID = 7,
    COREX_WIRE_STREAM_ID = 8,
    COREX_WIRE_EVENT_ID = 9,
    COREX_WIRE_MODULE_ID = 10,
    COREX_WIRE_KERNEL_ID = 11,
} CorexGeneratedWireType;
typedef struct { const char *name; uint32_t type; uint32_t wire_bytes; const char *object_kind; } CorexGeneratedFieldMetadata;
typedef struct { const char *name; uint32_t opcode; uint32_t capability_id; const char *implementation_class; uint32_t request_bytes; uint32_t response_bytes; const char *backend_binding; const CorexGeneratedFieldMetadata *request; size_t request_count; const CorexGeneratedFieldMetadata *response; size_t response_count; } CorexGeneratedApiMetadata;
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceSynchronize_request_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceSynchronize_response_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaStreamQuery_request_fields[] = {
    {"stream", COREX_WIRE_STREAM_ID, 8u, "stream"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaStreamQuery_response_fields[] = {
    {"state", COREX_WIRE_U32, 4u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaEventQuery_request_fields[] = {
    {"event", COREX_WIRE_EVENT_ID, 8u, "event"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaEventQuery_response_fields[] = {
    {"state", COREX_WIRE_U32, 4u, "none"},
};
static const CorexGeneratedApiMetadata corex_generated_apis[] = {
    {"cudaDeviceSynchronize", 4u, CRX_CAP_STREAM_EVENT, "semantic_rpc", 0u, 0u, "corex_backend_context_sync", corex_generated_cudaDeviceSynchronize_request_fields, 0u, corex_generated_cudaDeviceSynchronize_response_fields, 0u},
    {"cudaStreamQuery", 14u, CRX_CAP_STREAM_EVENT, "object_query", 8u, 4u, "corex_backend_stream_query", corex_generated_cudaStreamQuery_request_fields, 1u, corex_generated_cudaStreamQuery_response_fields, 1u},
    {"cudaEventQuery", 19u, CRX_CAP_STREAM_EVENT, "object_query", 8u, 4u, "corex_backend_event_query", corex_generated_cudaEventQuery_request_fields, 1u, corex_generated_cudaEventQuery_response_fields, 1u},
};
#define COREX_GENERATED_API_COUNT 3u
static inline int corex_generated_validate_payload(uint32_t opcode, size_t length)
{
    for (size_t i = 0; i < COREX_GENERATED_API_COUNT; ++i)
        if (corex_generated_apis[i].opcode == opcode)
            return length == corex_generated_apis[i].request_bytes ? 0 : -1;
    return -1; /* unknown schema entries never guess */
}
static inline int corex_generated_validate_response(uint32_t opcode, size_t length)
{
    for (size_t i = 0; i < COREX_GENERATED_API_COUNT; ++i)
        if (corex_generated_apis[i].opcode == opcode)
            return length == corex_generated_apis[i].response_bytes ? 0 : -1;
    return -1;
}
/* Registry metadata is in corex_generated_apis[]. */
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaDeviceSynchronizeRequest;
static inline int corex_generated_encode_cudaDeviceSynchronize_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceSynchronizeRequest *value)
{
    (void)output; (void)capacity;
    if (!value) return -1;
    size_t position = 0;
    return position == 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceSynchronize_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceSynchronizeRequest *value)
{
    (void)input;
    if (!value || length != 0u) return -1;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaDeviceSynchronizeResponse;
static inline int corex_generated_encode_cudaDeviceSynchronize_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceSynchronizeResponse *value)
{
    (void)output; (void)capacity;
    if (!value) return -1;
    size_t position = 0;
    return position == 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceSynchronize_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceSynchronizeResponse *value)
{
    (void)input;
    if (!value || length != 0u) return -1;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    uint64_t stream;
} CorexGeneratedcudaStreamQueryRequest;
static inline int corex_generated_encode_cudaStreamQuery_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaStreamQueryRequest *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 8u) return -1;
    size_t position = 0;
    corex_protocol_write_u64(output, &position, (uint64_t)value->stream);
    return position == 8u ? 0 : -1;
}
static inline int corex_generated_decode_cudaStreamQuery_request(const unsigned char *input, size_t length, CorexGeneratedcudaStreamQueryRequest *value)
{
    (void)input;
    if (!input || !value || length != 8u) return -1;
    size_t position = 0;
    uint64_t stream_wire; if (corex_protocol_take_u64(input, length, &position, &stream_wire) != 0) return -1; value->stream = (uint64_t)stream_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint32_t state;
} CorexGeneratedcudaStreamQueryResponse;
static inline int corex_generated_encode_cudaStreamQuery_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaStreamQueryResponse *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->state);
    return position == 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaStreamQuery_response(const unsigned char *input, size_t length, CorexGeneratedcudaStreamQueryResponse *value)
{
    (void)input;
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t state_wire; if (corex_protocol_take_u32(input, length, &position, &state_wire) != 0) return -1; value->state = (uint32_t)state_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint64_t event;
} CorexGeneratedcudaEventQueryRequest;
static inline int corex_generated_encode_cudaEventQuery_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaEventQueryRequest *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 8u) return -1;
    size_t position = 0;
    corex_protocol_write_u64(output, &position, (uint64_t)value->event);
    return position == 8u ? 0 : -1;
}
static inline int corex_generated_decode_cudaEventQuery_request(const unsigned char *input, size_t length, CorexGeneratedcudaEventQueryRequest *value)
{
    (void)input;
    if (!input || !value || length != 8u) return -1;
    size_t position = 0;
    uint64_t event_wire; if (corex_protocol_take_u64(input, length, &position, &event_wire) != 0) return -1; value->event = (uint64_t)event_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint32_t state;
} CorexGeneratedcudaEventQueryResponse;
static inline int corex_generated_encode_cudaEventQuery_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaEventQueryResponse *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->state);
    return position == 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaEventQuery_response(const unsigned char *input, size_t length, CorexGeneratedcudaEventQueryResponse *value)
{
    (void)input;
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t state_wire; if (corex_protocol_take_u32(input, length, &position, &state_wire) != 0) return -1; value->state = (uint32_t)state_wire;
    return position == length ? 0 : -1;
}
#endif
