/* Generated by scripts/generate-api-schema.py; DO NOT EDIT. */
#include "corex_api_schema.h"
#include <stdio.h>
int main(void) {
    if (COREX_GENERATED_API_COUNT != 3u) return 1;
    if (corex_generated_validate_payload(4u, 0u) != 0) return 1;
    if (corex_generated_validate_response(4u, 0u) != 0) return 1;
    (void)corex_generated_cudaDeviceSynchronize_request_fields;
    if (corex_generated_validate_payload(14u, 8u) != 0) return 1;
    if (corex_generated_validate_response(14u, 4u) != 0) return 1;
    (void)corex_generated_cudaStreamQuery_request_fields;
    if (corex_generated_validate_payload(19u, 8u) != 0) return 1;
    if (corex_generated_validate_response(19u, 4u) != 0) return 1;
    (void)corex_generated_cudaEventQuery_request_fields;
    if (corex_generated_validate_payload(999u, 0) == 0 ||
        corex_generated_validate_response(999u, 0) == 0 ||
        corex_generated_validate_payload(OP_STREAM_QUERY, 7) == 0) return 1;
    puts("M3_S6_GENERATED_SCHEMA_TEST=PASS");
    return 0;
}
