/* Generated by scripts/generate-api-schema.py; DO NOT EDIT. */
#ifndef COREX_GENERATED_API_SCHEMA_H
#define COREX_GENERATED_API_SCHEMA_H
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "corex_protocol.h"
typedef enum {
    COREX_WIRE_U32 = 1,
    COREX_WIRE_I32 = 2,
    COREX_WIRE_U64 = 3,
    COREX_WIRE_I64 = 4,
    COREX_WIRE_SIZE_U64 = 5,
    COREX_WIRE_BOOL_U32 = 6,
    COREX_WIRE_ALLOCATION_ID = 7,
    COREX_WIRE_STREAM_ID = 8,
    COREX_WIRE_EVENT_ID = 9,
    COREX_WIRE_MODULE_ID = 10,
    COREX_WIRE_KERNEL_ID = 11,
    COREX_WIRE_BOUNDED_BYTES = 12,
    COREX_WIRE_BOUNDED_STRING = 13,
} CorexGeneratedWireType;
typedef struct { const char *name; uint32_t type; uint32_t min_wire_bytes; uint32_t max_wire_bytes; uint32_t max_payload_bytes; const char *object_kind; } CorexGeneratedFieldMetadata;
typedef struct { const char *name; uint32_t opcode; uint32_t capability_id; const char *implementation_class; uint32_t request_min_bytes; uint32_t request_max_bytes; uint32_t response_min_bytes; uint32_t response_max_bytes; const char *backend_binding; const char *server_handler; const CorexGeneratedFieldMetadata *request; size_t request_count; const CorexGeneratedFieldMetadata *response; size_t response_count; } CorexGeneratedApiMetadata;
typedef int (*CorexGeneratedRpcCall)(uint32_t, const unsigned char *, uint32_t, unsigned char **, uint32_t *);
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceSynchronize_request_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceSynchronize_response_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaStreamQuery_request_fields[] = {
    {"stream", COREX_WIRE_STREAM_ID, 8u, 8u, 0u, "stream"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaStreamQuery_response_fields[] = {
    {"state", COREX_WIRE_U32, 4u, 4u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaEventQuery_request_fields[] = {
    {"event", COREX_WIRE_EVENT_ID, 8u, 8u, 0u, "event"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaEventQuery_response_fields[] = {
    {"state", COREX_WIRE_U32, 4u, 4u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetAttribute_request_fields[] = {
    {"attribute", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
    {"device", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetAttribute_response_fields[] = {
    {"value", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaGetDeviceFlags_request_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaGetDeviceFlags_response_fields[] = {
    {"flags", COREX_WIRE_U32, 4u, 4u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetStreamPriorityRange_request_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetStreamPriorityRange_response_fields[] = {
    {"least_priority", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
    {"greatest_priority", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetLimit_request_fields[] = {
    {"limit", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetLimit_response_fields[] = {
    {"value", COREX_WIRE_SIZE_U64, 8u, 8u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetCacheConfig_request_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetCacheConfig_response_fields[] = {
    {"config", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetSharedMemConfig_request_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetSharedMemConfig_response_fields[] = {
    {"config", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaFuncSetAttribute_request_fields[] = {
    {"kernel", COREX_WIRE_KERNEL_ID, 8u, 8u, 0u, "kernel"},
    {"attribute", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
    {"value", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaFuncSetAttribute_response_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaFuncSetCacheConfig_request_fields[] = {
    {"kernel", COREX_WIRE_KERNEL_ID, 8u, 8u, 0u, "kernel"},
    {"config", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaFuncSetCacheConfig_response_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetPCIBusId_request_fields[] = {
    {"device", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetPCIBusId_response_fields[] = {
    {"pci_bus_id", COREX_WIRE_BOUNDED_STRING, 4u, 36u, 32u, "none"},
};
#define COREX_GENERATED_CUDADEVICEGETPCIBUSID_RESPONSE_PCI_BUS_ID_MAX_BYTES 32u
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetByPCIBusId_request_fields[] = {
    {"pci_bus_id", COREX_WIRE_BOUNDED_STRING, 4u, 36u, 32u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetByPCIBusId_response_fields[] = {
    {"device", COREX_WIRE_I32, 4u, 4u, 0u, "none"},
};
#define COREX_GENERATED_CUDADEVICEGETBYPCIBUSID_REQUEST_PCI_BUS_ID_MAX_BYTES 32u
static const CorexGeneratedApiMetadata corex_generated_apis[] = {
    {"cudaDeviceSynchronize", 4u, CRX_CAP_STREAM_EVENT, "semantic_rpc", 0u, 0u, 0u, 0u, "corex_backend_context_sync", "handle_sync", corex_generated_cudaDeviceSynchronize_request_fields, 0u, corex_generated_cudaDeviceSynchronize_response_fields, 0u},
    {"cudaStreamQuery", 14u, CRX_CAP_STREAM_EVENT, "object_query", 8u, 8u, 4u, 4u, "corex_backend_stream_query", "handle_stream_query", corex_generated_cudaStreamQuery_request_fields, 1u, corex_generated_cudaStreamQuery_response_fields, 1u},
    {"cudaEventQuery", 19u, CRX_CAP_STREAM_EVENT, "object_query", 8u, 8u, 4u, 4u, "corex_backend_event_query", "handle_event_query", corex_generated_cudaEventQuery_request_fields, 1u, corex_generated_cudaEventQuery_response_fields, 1u},
    {"cudaDeviceGetAttribute", 39u, CRX_CAP_DEVICE_INFO, "scalar_query", 8u, 8u, 4u, 4u, "corex_backend_device_attribute", "handle_device_get_attribute", corex_generated_cudaDeviceGetAttribute_request_fields, 2u, corex_generated_cudaDeviceGetAttribute_response_fields, 1u},
    {"cudaGetDeviceFlags", 40u, CRX_CAP_DEVICE_INFO, "scalar_query", 0u, 0u, 4u, 4u, "corex_backend_context_get_flags", "handle_get_device_flags", corex_generated_cudaGetDeviceFlags_request_fields, 0u, corex_generated_cudaGetDeviceFlags_response_fields, 1u},
    {"cudaDeviceGetStreamPriorityRange", 41u, CRX_CAP_STREAM_EVENT, "scalar_query", 0u, 0u, 8u, 8u, "corex_backend_stream_priority_range", "handle_get_priority_range", corex_generated_cudaDeviceGetStreamPriorityRange_request_fields, 0u, corex_generated_cudaDeviceGetStreamPriorityRange_response_fields, 2u},
    {"cudaDeviceGetLimit", 42u, CRX_CAP_DEVICE_INFO, "scalar_query", 4u, 4u, 8u, 8u, "corex_backend_context_get_limit", "handle_get_limit", corex_generated_cudaDeviceGetLimit_request_fields, 1u, corex_generated_cudaDeviceGetLimit_response_fields, 1u},
    {"cudaDeviceGetCacheConfig", 43u, CRX_CAP_DEVICE_INFO, "scalar_query", 0u, 0u, 4u, 4u, "corex_backend_context_get_cache_config", "handle_get_cache_config", corex_generated_cudaDeviceGetCacheConfig_request_fields, 0u, corex_generated_cudaDeviceGetCacheConfig_response_fields, 1u},
    {"cudaDeviceGetSharedMemConfig", 44u, CRX_CAP_DEVICE_INFO, "scalar_query", 0u, 0u, 4u, 4u, "corex_backend_context_get_shared_mem_config", "handle_get_shared_mem_config", corex_generated_cudaDeviceGetSharedMemConfig_request_fields, 0u, corex_generated_cudaDeviceGetSharedMemConfig_response_fields, 1u},
    {"cudaFuncSetAttribute", 45u, CRX_CAP_MODULE_KERNEL, "semantic_rpc", 16u, 16u, 0u, 0u, "corex_backend_function_set_attribute", "handle_function_set_attribute", corex_generated_cudaFuncSetAttribute_request_fields, 3u, corex_generated_cudaFuncSetAttribute_response_fields, 0u},
    {"cudaFuncSetCacheConfig", 46u, CRX_CAP_MODULE_KERNEL, "semantic_rpc", 12u, 12u, 0u, 0u, "corex_backend_function_set_cache_config", "handle_function_set_cache_config", corex_generated_cudaFuncSetCacheConfig_request_fields, 2u, corex_generated_cudaFuncSetCacheConfig_response_fields, 0u},
    {"cudaDeviceGetPCIBusId", 47u, CRX_CAP_DEVICE_INFO, "scalar_query", 4u, 4u, 4u, 36u, "corex_backend_device_pci_bus_id", "handle_device_get_pci_bus_id", corex_generated_cudaDeviceGetPCIBusId_request_fields, 1u, corex_generated_cudaDeviceGetPCIBusId_response_fields, 1u},
    {"cudaDeviceGetByPCIBusId", 48u, CRX_CAP_DEVICE_INFO, "scalar_query", 4u, 36u, 4u, 4u, "corex_backend_device_get_by_pci_bus_id", "handle_device_get_by_pci_bus_id", corex_generated_cudaDeviceGetByPCIBusId_request_fields, 1u, corex_generated_cudaDeviceGetByPCIBusId_response_fields, 1u},
};
#define COREX_GENERATED_API_COUNT 13u
static inline int corex_generated_validate_payload(uint32_t opcode, size_t length)
{
    for (size_t i = 0; i < COREX_GENERATED_API_COUNT; ++i)
        if (corex_generated_apis[i].opcode == opcode)
            return length >= corex_generated_apis[i].request_min_bytes && length <= corex_generated_apis[i].request_max_bytes ? 0 : -1;
    return -1; /* unknown schema entries never guess */
}
static inline int corex_generated_validate_response(uint32_t opcode, size_t length)
{
    for (size_t i = 0; i < COREX_GENERATED_API_COUNT; ++i)
        if (corex_generated_apis[i].opcode == opcode)
            return length >= corex_generated_apis[i].response_min_bytes && length <= corex_generated_apis[i].response_max_bytes ? 0 : -1;
    return -1;
}
/* Schema-owned server registrations are generated from reviewed metadata. */
#define COREX_GENERATED_SERVER_HANDLER_REGISTRY(X) \
    X(4u, handle_sync, CRX_CAP_STREAM_EVENT) \
    X(14u, handle_stream_query, CRX_CAP_STREAM_EVENT) \
    X(19u, handle_event_query, CRX_CAP_STREAM_EVENT) \
    X(39u, handle_device_get_attribute, CRX_CAP_DEVICE_INFO) \
    X(40u, handle_get_device_flags, CRX_CAP_DEVICE_INFO) \
    X(41u, handle_get_priority_range, CRX_CAP_STREAM_EVENT) \
    X(42u, handle_get_limit, CRX_CAP_DEVICE_INFO) \
    X(43u, handle_get_cache_config, CRX_CAP_DEVICE_INFO) \
    X(44u, handle_get_shared_mem_config, CRX_CAP_DEVICE_INFO) \
    X(45u, handle_function_set_attribute, CRX_CAP_MODULE_KERNEL) \
    X(46u, handle_function_set_cache_config, CRX_CAP_MODULE_KERNEL) \
    X(47u, handle_device_get_pci_bus_id, CRX_CAP_DEVICE_INFO) \
    X(48u, handle_device_get_by_pci_bus_id, CRX_CAP_DEVICE_INFO)
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaDeviceSynchronizeRequest;
static inline int corex_generated_encode_cudaDeviceSynchronize_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceSynchronizeRequest *value)
{
    if (!encoded_length || !value) return -1;
    (void)output; (void)capacity;
    size_t position = 0;
    *encoded_length = position;
    return position <= 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceSynchronize_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceSynchronizeRequest *value)
{
    if (!value || length != 0u) return -1;
    (void)input;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaDeviceSynchronizeResponse;
static inline int corex_generated_encode_cudaDeviceSynchronize_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceSynchronizeResponse *value)
{
    if (!encoded_length || !value) return -1;
    (void)output; (void)capacity;
    size_t position = 0;
    *encoded_length = position;
    return position <= 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceSynchronize_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceSynchronizeResponse *value)
{
    if (!value || length != 0u) return -1;
    (void)input;
    size_t position = 0;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaDeviceSynchronize(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaDeviceSynchronizeRequest *request, CorexGeneratedcudaDeviceSynchronizeResponse *response)
{
    unsigned char request_wire[1u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaDeviceSynchronize_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(4u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaDeviceSynchronize_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
typedef struct {
    uint64_t stream;
} CorexGeneratedcudaStreamQueryRequest;
static inline int corex_generated_encode_cudaStreamQuery_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaStreamQueryRequest *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 8u) return -1;
    size_t position = 0;
    corex_protocol_write_u64(output, &position, (uint64_t)value->stream);
    *encoded_length = position;
    return position <= 8u ? 0 : -1;
}
static inline int corex_generated_decode_cudaStreamQuery_request(const unsigned char *input, size_t length, CorexGeneratedcudaStreamQueryRequest *value)
{
    if (!input || !value || length != 8u) return -1;
    size_t position = 0;
    uint64_t stream_wire; if (corex_protocol_take_u64(input, length, &position, &stream_wire) != 0) return -1; value->stream = (uint64_t)stream_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint32_t state;
} CorexGeneratedcudaStreamQueryResponse;
static inline int corex_generated_encode_cudaStreamQuery_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaStreamQueryResponse *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->state);
    *encoded_length = position;
    return position <= 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaStreamQuery_response(const unsigned char *input, size_t length, CorexGeneratedcudaStreamQueryResponse *value)
{
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t state_wire; if (corex_protocol_take_u32(input, length, &position, &state_wire) != 0) return -1; value->state = (uint32_t)state_wire;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaStreamQuery(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaStreamQueryRequest *request, CorexGeneratedcudaStreamQueryResponse *response)
{
    unsigned char request_wire[8u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaStreamQuery_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(14u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaStreamQuery_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
typedef struct {
    uint64_t event;
} CorexGeneratedcudaEventQueryRequest;
static inline int corex_generated_encode_cudaEventQuery_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaEventQueryRequest *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 8u) return -1;
    size_t position = 0;
    corex_protocol_write_u64(output, &position, (uint64_t)value->event);
    *encoded_length = position;
    return position <= 8u ? 0 : -1;
}
static inline int corex_generated_decode_cudaEventQuery_request(const unsigned char *input, size_t length, CorexGeneratedcudaEventQueryRequest *value)
{
    if (!input || !value || length != 8u) return -1;
    size_t position = 0;
    uint64_t event_wire; if (corex_protocol_take_u64(input, length, &position, &event_wire) != 0) return -1; value->event = (uint64_t)event_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint32_t state;
} CorexGeneratedcudaEventQueryResponse;
static inline int corex_generated_encode_cudaEventQuery_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaEventQueryResponse *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->state);
    *encoded_length = position;
    return position <= 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaEventQuery_response(const unsigned char *input, size_t length, CorexGeneratedcudaEventQueryResponse *value)
{
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t state_wire; if (corex_protocol_take_u32(input, length, &position, &state_wire) != 0) return -1; value->state = (uint32_t)state_wire;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaEventQuery(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaEventQueryRequest *request, CorexGeneratedcudaEventQueryResponse *response)
{
    unsigned char request_wire[8u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaEventQuery_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(19u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaEventQuery_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
typedef struct {
    int32_t attribute;
    int32_t device;
} CorexGeneratedcudaDeviceGetAttributeRequest;
static inline int corex_generated_encode_cudaDeviceGetAttribute_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetAttributeRequest *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 8u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->attribute);
    corex_protocol_write_u32(output, &position, (uint32_t)value->device);
    *encoded_length = position;
    return position <= 8u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetAttribute_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetAttributeRequest *value)
{
    if (!input || !value || length != 8u) return -1;
    size_t position = 0;
    uint32_t attribute_wire; if (corex_protocol_take_u32(input, length, &position, &attribute_wire) != 0) return -1; value->attribute = (int32_t)attribute_wire;
    uint32_t device_wire; if (corex_protocol_take_u32(input, length, &position, &device_wire) != 0) return -1; value->device = (int32_t)device_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    int32_t value;
} CorexGeneratedcudaDeviceGetAttributeResponse;
static inline int corex_generated_encode_cudaDeviceGetAttribute_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetAttributeResponse *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->value);
    *encoded_length = position;
    return position <= 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetAttribute_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetAttributeResponse *value)
{
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t value_wire; if (corex_protocol_take_u32(input, length, &position, &value_wire) != 0) return -1; value->value = (int32_t)value_wire;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaDeviceGetAttribute(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaDeviceGetAttributeRequest *request, CorexGeneratedcudaDeviceGetAttributeResponse *response)
{
    unsigned char request_wire[8u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaDeviceGetAttribute_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(39u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaDeviceGetAttribute_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaGetDeviceFlagsRequest;
static inline int corex_generated_encode_cudaGetDeviceFlags_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaGetDeviceFlagsRequest *value)
{
    if (!encoded_length || !value) return -1;
    (void)output; (void)capacity;
    size_t position = 0;
    *encoded_length = position;
    return position <= 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaGetDeviceFlags_request(const unsigned char *input, size_t length, CorexGeneratedcudaGetDeviceFlagsRequest *value)
{
    if (!value || length != 0u) return -1;
    (void)input;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    uint32_t flags;
} CorexGeneratedcudaGetDeviceFlagsResponse;
static inline int corex_generated_encode_cudaGetDeviceFlags_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaGetDeviceFlagsResponse *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->flags);
    *encoded_length = position;
    return position <= 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaGetDeviceFlags_response(const unsigned char *input, size_t length, CorexGeneratedcudaGetDeviceFlagsResponse *value)
{
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t flags_wire; if (corex_protocol_take_u32(input, length, &position, &flags_wire) != 0) return -1; value->flags = (uint32_t)flags_wire;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaGetDeviceFlags(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaGetDeviceFlagsRequest *request, CorexGeneratedcudaGetDeviceFlagsResponse *response)
{
    unsigned char request_wire[1u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaGetDeviceFlags_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(40u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaGetDeviceFlags_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaDeviceGetStreamPriorityRangeRequest;
static inline int corex_generated_encode_cudaDeviceGetStreamPriorityRange_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetStreamPriorityRangeRequest *value)
{
    if (!encoded_length || !value) return -1;
    (void)output; (void)capacity;
    size_t position = 0;
    *encoded_length = position;
    return position <= 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetStreamPriorityRange_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetStreamPriorityRangeRequest *value)
{
    if (!value || length != 0u) return -1;
    (void)input;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    int32_t least_priority;
    int32_t greatest_priority;
} CorexGeneratedcudaDeviceGetStreamPriorityRangeResponse;
static inline int corex_generated_encode_cudaDeviceGetStreamPriorityRange_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetStreamPriorityRangeResponse *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 8u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->least_priority);
    corex_protocol_write_u32(output, &position, (uint32_t)value->greatest_priority);
    *encoded_length = position;
    return position <= 8u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetStreamPriorityRange_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetStreamPriorityRangeResponse *value)
{
    if (!input || !value || length != 8u) return -1;
    size_t position = 0;
    uint32_t least_priority_wire; if (corex_protocol_take_u32(input, length, &position, &least_priority_wire) != 0) return -1; value->least_priority = (int32_t)least_priority_wire;
    uint32_t greatest_priority_wire; if (corex_protocol_take_u32(input, length, &position, &greatest_priority_wire) != 0) return -1; value->greatest_priority = (int32_t)greatest_priority_wire;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaDeviceGetStreamPriorityRange(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaDeviceGetStreamPriorityRangeRequest *request, CorexGeneratedcudaDeviceGetStreamPriorityRangeResponse *response)
{
    unsigned char request_wire[1u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaDeviceGetStreamPriorityRange_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(41u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaDeviceGetStreamPriorityRange_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
typedef struct {
    int32_t limit;
} CorexGeneratedcudaDeviceGetLimitRequest;
static inline int corex_generated_encode_cudaDeviceGetLimit_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetLimitRequest *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->limit);
    *encoded_length = position;
    return position <= 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetLimit_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetLimitRequest *value)
{
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t limit_wire; if (corex_protocol_take_u32(input, length, &position, &limit_wire) != 0) return -1; value->limit = (int32_t)limit_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint64_t value;
} CorexGeneratedcudaDeviceGetLimitResponse;
static inline int corex_generated_encode_cudaDeviceGetLimit_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetLimitResponse *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 8u) return -1;
    size_t position = 0;
    corex_protocol_write_u64(output, &position, (uint64_t)value->value);
    *encoded_length = position;
    return position <= 8u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetLimit_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetLimitResponse *value)
{
    if (!input || !value || length != 8u) return -1;
    size_t position = 0;
    uint64_t value_wire; if (corex_protocol_take_u64(input, length, &position, &value_wire) != 0) return -1; value->value = (uint64_t)value_wire;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaDeviceGetLimit(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaDeviceGetLimitRequest *request, CorexGeneratedcudaDeviceGetLimitResponse *response)
{
    unsigned char request_wire[4u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaDeviceGetLimit_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(42u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaDeviceGetLimit_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaDeviceGetCacheConfigRequest;
static inline int corex_generated_encode_cudaDeviceGetCacheConfig_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetCacheConfigRequest *value)
{
    if (!encoded_length || !value) return -1;
    (void)output; (void)capacity;
    size_t position = 0;
    *encoded_length = position;
    return position <= 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetCacheConfig_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetCacheConfigRequest *value)
{
    if (!value || length != 0u) return -1;
    (void)input;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    int32_t config;
} CorexGeneratedcudaDeviceGetCacheConfigResponse;
static inline int corex_generated_encode_cudaDeviceGetCacheConfig_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetCacheConfigResponse *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->config);
    *encoded_length = position;
    return position <= 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetCacheConfig_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetCacheConfigResponse *value)
{
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t config_wire; if (corex_protocol_take_u32(input, length, &position, &config_wire) != 0) return -1; value->config = (int32_t)config_wire;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaDeviceGetCacheConfig(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaDeviceGetCacheConfigRequest *request, CorexGeneratedcudaDeviceGetCacheConfigResponse *response)
{
    unsigned char request_wire[1u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaDeviceGetCacheConfig_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(43u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaDeviceGetCacheConfig_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaDeviceGetSharedMemConfigRequest;
static inline int corex_generated_encode_cudaDeviceGetSharedMemConfig_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetSharedMemConfigRequest *value)
{
    if (!encoded_length || !value) return -1;
    (void)output; (void)capacity;
    size_t position = 0;
    *encoded_length = position;
    return position <= 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetSharedMemConfig_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetSharedMemConfigRequest *value)
{
    if (!value || length != 0u) return -1;
    (void)input;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    int32_t config;
} CorexGeneratedcudaDeviceGetSharedMemConfigResponse;
static inline int corex_generated_encode_cudaDeviceGetSharedMemConfig_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetSharedMemConfigResponse *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->config);
    *encoded_length = position;
    return position <= 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetSharedMemConfig_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetSharedMemConfigResponse *value)
{
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t config_wire; if (corex_protocol_take_u32(input, length, &position, &config_wire) != 0) return -1; value->config = (int32_t)config_wire;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaDeviceGetSharedMemConfig(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaDeviceGetSharedMemConfigRequest *request, CorexGeneratedcudaDeviceGetSharedMemConfigResponse *response)
{
    unsigned char request_wire[1u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaDeviceGetSharedMemConfig_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(44u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaDeviceGetSharedMemConfig_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
typedef struct {
    uint64_t kernel;
    int32_t attribute;
    int32_t value;
} CorexGeneratedcudaFuncSetAttributeRequest;
static inline int corex_generated_encode_cudaFuncSetAttribute_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaFuncSetAttributeRequest *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 16u) return -1;
    size_t position = 0;
    corex_protocol_write_u64(output, &position, (uint64_t)value->kernel);
    corex_protocol_write_u32(output, &position, (uint32_t)value->attribute);
    corex_protocol_write_u32(output, &position, (uint32_t)value->value);
    *encoded_length = position;
    return position <= 16u ? 0 : -1;
}
static inline int corex_generated_decode_cudaFuncSetAttribute_request(const unsigned char *input, size_t length, CorexGeneratedcudaFuncSetAttributeRequest *value)
{
    if (!input || !value || length != 16u) return -1;
    size_t position = 0;
    uint64_t kernel_wire; if (corex_protocol_take_u64(input, length, &position, &kernel_wire) != 0) return -1; value->kernel = (uint64_t)kernel_wire;
    uint32_t attribute_wire; if (corex_protocol_take_u32(input, length, &position, &attribute_wire) != 0) return -1; value->attribute = (int32_t)attribute_wire;
    uint32_t value_wire; if (corex_protocol_take_u32(input, length, &position, &value_wire) != 0) return -1; value->value = (int32_t)value_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaFuncSetAttributeResponse;
static inline int corex_generated_encode_cudaFuncSetAttribute_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaFuncSetAttributeResponse *value)
{
    if (!encoded_length || !value) return -1;
    (void)output; (void)capacity;
    size_t position = 0;
    *encoded_length = position;
    return position <= 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaFuncSetAttribute_response(const unsigned char *input, size_t length, CorexGeneratedcudaFuncSetAttributeResponse *value)
{
    if (!value || length != 0u) return -1;
    (void)input;
    size_t position = 0;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaFuncSetAttribute(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaFuncSetAttributeRequest *request, CorexGeneratedcudaFuncSetAttributeResponse *response)
{
    unsigned char request_wire[16u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaFuncSetAttribute_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(45u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaFuncSetAttribute_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
typedef struct {
    uint64_t kernel;
    int32_t config;
} CorexGeneratedcudaFuncSetCacheConfigRequest;
static inline int corex_generated_encode_cudaFuncSetCacheConfig_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaFuncSetCacheConfigRequest *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 12u) return -1;
    size_t position = 0;
    corex_protocol_write_u64(output, &position, (uint64_t)value->kernel);
    corex_protocol_write_u32(output, &position, (uint32_t)value->config);
    *encoded_length = position;
    return position <= 12u ? 0 : -1;
}
static inline int corex_generated_decode_cudaFuncSetCacheConfig_request(const unsigned char *input, size_t length, CorexGeneratedcudaFuncSetCacheConfigRequest *value)
{
    if (!input || !value || length != 12u) return -1;
    size_t position = 0;
    uint64_t kernel_wire; if (corex_protocol_take_u64(input, length, &position, &kernel_wire) != 0) return -1; value->kernel = (uint64_t)kernel_wire;
    uint32_t config_wire; if (corex_protocol_take_u32(input, length, &position, &config_wire) != 0) return -1; value->config = (int32_t)config_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaFuncSetCacheConfigResponse;
static inline int corex_generated_encode_cudaFuncSetCacheConfig_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaFuncSetCacheConfigResponse *value)
{
    if (!encoded_length || !value) return -1;
    (void)output; (void)capacity;
    size_t position = 0;
    *encoded_length = position;
    return position <= 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaFuncSetCacheConfig_response(const unsigned char *input, size_t length, CorexGeneratedcudaFuncSetCacheConfigResponse *value)
{
    if (!value || length != 0u) return -1;
    (void)input;
    size_t position = 0;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaFuncSetCacheConfig(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaFuncSetCacheConfigRequest *request, CorexGeneratedcudaFuncSetCacheConfigResponse *response)
{
    unsigned char request_wire[12u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaFuncSetCacheConfig_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(46u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaFuncSetCacheConfig_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
typedef struct {
    int32_t device;
} CorexGeneratedcudaDeviceGetPCIBusIdRequest;
static inline int corex_generated_encode_cudaDeviceGetPCIBusId_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetPCIBusIdRequest *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->device);
    *encoded_length = position;
    return position <= 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetPCIBusId_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetPCIBusIdRequest *value)
{
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t device_wire; if (corex_protocol_take_u32(input, length, &position, &device_wire) != 0) return -1; value->device = (int32_t)device_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint32_t pci_bus_id_length;
    char pci_bus_id[COREX_GENERATED_CUDADEVICEGETPCIBUSID_RESPONSE_PCI_BUS_ID_MAX_BYTES + 1u];
} CorexGeneratedcudaDeviceGetPCIBusIdResponse;
static inline int corex_generated_encode_cudaDeviceGetPCIBusId_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetPCIBusIdResponse *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 4u) return -1;
    size_t position = 0;
    if (value->pci_bus_id_length > COREX_GENERATED_CUDADEVICEGETPCIBUSID_RESPONSE_PCI_BUS_ID_MAX_BYTES) return -1;
    if (value->pci_bus_id[value->pci_bus_id_length] != '\0' || memchr(value->pci_bus_id, '\0', value->pci_bus_id_length) != NULL) return -1;
    if (position > capacity || capacity - position < 4u + value->pci_bus_id_length) return -1;
    corex_protocol_write_u32(output, &position, value->pci_bus_id_length);
    if (value->pci_bus_id_length) memcpy(output + position, value->pci_bus_id, value->pci_bus_id_length);
    position += value->pci_bus_id_length;
    *encoded_length = position;
    return position <= 36u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetPCIBusId_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetPCIBusIdResponse *value)
{
    if (!input || !value || length < 4u || length > 36u) return -1;
    size_t position = 0;
    uint32_t pci_bus_id_length; if (corex_protocol_take_u32(input, length, &position, &pci_bus_id_length) != 0 || pci_bus_id_length > COREX_GENERATED_CUDADEVICEGETPCIBUSID_RESPONSE_PCI_BUS_ID_MAX_BYTES || pci_bus_id_length > length - position) return -1;
    if (memchr(input + position, '\0', pci_bus_id_length) != NULL) return -1;
    if (pci_bus_id_length) memcpy(value->pci_bus_id, input + position, pci_bus_id_length);
    value->pci_bus_id[pci_bus_id_length] = '\0';
    value->pci_bus_id_length = pci_bus_id_length; position += pci_bus_id_length;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaDeviceGetPCIBusId(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaDeviceGetPCIBusIdRequest *request, CorexGeneratedcudaDeviceGetPCIBusIdResponse *response)
{
    unsigned char request_wire[4u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaDeviceGetPCIBusId_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(47u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaDeviceGetPCIBusId_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
typedef struct {
    uint32_t pci_bus_id_length;
    char pci_bus_id[COREX_GENERATED_CUDADEVICEGETBYPCIBUSID_REQUEST_PCI_BUS_ID_MAX_BYTES + 1u];
} CorexGeneratedcudaDeviceGetByPCIBusIdRequest;
static inline int corex_generated_encode_cudaDeviceGetByPCIBusId_request(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetByPCIBusIdRequest *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 4u) return -1;
    size_t position = 0;
    if (value->pci_bus_id_length > COREX_GENERATED_CUDADEVICEGETBYPCIBUSID_REQUEST_PCI_BUS_ID_MAX_BYTES) return -1;
    if (value->pci_bus_id[value->pci_bus_id_length] != '\0' || memchr(value->pci_bus_id, '\0', value->pci_bus_id_length) != NULL) return -1;
    if (position > capacity || capacity - position < 4u + value->pci_bus_id_length) return -1;
    corex_protocol_write_u32(output, &position, value->pci_bus_id_length);
    if (value->pci_bus_id_length) memcpy(output + position, value->pci_bus_id, value->pci_bus_id_length);
    position += value->pci_bus_id_length;
    *encoded_length = position;
    return position <= 36u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetByPCIBusId_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetByPCIBusIdRequest *value)
{
    if (!input || !value || length < 4u || length > 36u) return -1;
    size_t position = 0;
    uint32_t pci_bus_id_length; if (corex_protocol_take_u32(input, length, &position, &pci_bus_id_length) != 0 || pci_bus_id_length > COREX_GENERATED_CUDADEVICEGETBYPCIBUSID_REQUEST_PCI_BUS_ID_MAX_BYTES || pci_bus_id_length > length - position) return -1;
    if (memchr(input + position, '\0', pci_bus_id_length) != NULL) return -1;
    if (pci_bus_id_length) memcpy(value->pci_bus_id, input + position, pci_bus_id_length);
    value->pci_bus_id[pci_bus_id_length] = '\0';
    value->pci_bus_id_length = pci_bus_id_length; position += pci_bus_id_length;
    return position == length ? 0 : -1;
}
typedef struct {
    int32_t device;
} CorexGeneratedcudaDeviceGetByPCIBusIdResponse;
static inline int corex_generated_encode_cudaDeviceGetByPCIBusId_response(unsigned char *output, size_t capacity, size_t *encoded_length, const CorexGeneratedcudaDeviceGetByPCIBusIdResponse *value)
{
    if (!encoded_length || !value) return -1;
    if (!output || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->device);
    *encoded_length = position;
    return position <= 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetByPCIBusId_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetByPCIBusIdResponse *value)
{
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t device_wire; if (corex_protocol_take_u32(input, length, &position, &device_wire) != 0) return -1; value->device = (int32_t)device_wire;
    return position == length ? 0 : -1;
}
static inline int corex_generated_call_cudaDeviceGetByPCIBusId(CorexGeneratedRpcCall rpc_call, const CorexGeneratedcudaDeviceGetByPCIBusIdRequest *request, CorexGeneratedcudaDeviceGetByPCIBusIdResponse *response)
{
    unsigned char request_wire[36u];
    size_t request_length = 0;
    unsigned char *response_wire = NULL;
    uint32_t response_length = 0;
    if (!rpc_call || !request || !response ||
        corex_generated_encode_cudaDeviceGetByPCIBusId_request(request_wire, sizeof(request_wire), &request_length, request) != 0)
        return -1;
    if (rpc_call(48u, request_wire, (uint32_t)request_length, &response_wire, &response_length) != 0) {
        free(response_wire);
        return -1;
    }
    int result = corex_generated_decode_cudaDeviceGetByPCIBusId_response(response_wire, response_length, response);
    free(response_wire);
    return result;
}
#endif
