/* Generated by scripts/generate-api-schema.py; DO NOT EDIT. */
#ifndef COREX_GENERATED_API_SCHEMA_H
#define COREX_GENERATED_API_SCHEMA_H
#include <stddef.h>
#include <stdint.h>
#include "corex_protocol.h"
typedef enum {
    COREX_WIRE_U32 = 1,
    COREX_WIRE_I32 = 2,
    COREX_WIRE_U64 = 3,
    COREX_WIRE_I64 = 4,
    COREX_WIRE_SIZE_U64 = 5,
    COREX_WIRE_BOOL_U32 = 6,
    COREX_WIRE_ALLOCATION_ID = 7,
    COREX_WIRE_STREAM_ID = 8,
    COREX_WIRE_EVENT_ID = 9,
    COREX_WIRE_MODULE_ID = 10,
    COREX_WIRE_KERNEL_ID = 11,
} CorexGeneratedWireType;
typedef struct { const char *name; uint32_t type; uint32_t wire_bytes; const char *object_kind; } CorexGeneratedFieldMetadata;
typedef struct { const char *name; uint32_t opcode; uint32_t capability_id; const char *implementation_class; uint32_t request_bytes; uint32_t response_bytes; const char *backend_binding; const CorexGeneratedFieldMetadata *request; size_t request_count; const CorexGeneratedFieldMetadata *response; size_t response_count; } CorexGeneratedApiMetadata;
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceSynchronize_request_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceSynchronize_response_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaStreamQuery_request_fields[] = {
    {"stream", COREX_WIRE_STREAM_ID, 8u, "stream"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaStreamQuery_response_fields[] = {
    {"state", COREX_WIRE_U32, 4u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaEventQuery_request_fields[] = {
    {"event", COREX_WIRE_EVENT_ID, 8u, "event"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaEventQuery_response_fields[] = {
    {"state", COREX_WIRE_U32, 4u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetAttribute_request_fields[] = {
    {"attribute", COREX_WIRE_I32, 4u, "none"},
    {"device", COREX_WIRE_I32, 4u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetAttribute_response_fields[] = {
    {"value", COREX_WIRE_I32, 4u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaGetDeviceFlags_request_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaGetDeviceFlags_response_fields[] = {
    {"flags", COREX_WIRE_U32, 4u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetStreamPriorityRange_request_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetStreamPriorityRange_response_fields[] = {
    {"least_priority", COREX_WIRE_I32, 4u, "none"},
    {"greatest_priority", COREX_WIRE_I32, 4u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetLimit_request_fields[] = {
    {"limit", COREX_WIRE_I32, 4u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetLimit_response_fields[] = {
    {"value", COREX_WIRE_SIZE_U64, 8u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetCacheConfig_request_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetCacheConfig_response_fields[] = {
    {"config", COREX_WIRE_I32, 4u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetSharedMemConfig_request_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaDeviceGetSharedMemConfig_response_fields[] = {
    {"config", COREX_WIRE_I32, 4u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaFuncSetAttribute_request_fields[] = {
    {"kernel", COREX_WIRE_KERNEL_ID, 8u, "kernel"},
    {"attribute", COREX_WIRE_I32, 4u, "none"},
    {"value", COREX_WIRE_I32, 4u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaFuncSetAttribute_response_fields[] = {
};
static const CorexGeneratedFieldMetadata corex_generated_cudaFuncSetCacheConfig_request_fields[] = {
    {"kernel", COREX_WIRE_KERNEL_ID, 8u, "kernel"},
    {"config", COREX_WIRE_I32, 4u, "none"},
};
static const CorexGeneratedFieldMetadata corex_generated_cudaFuncSetCacheConfig_response_fields[] = {
};
static const CorexGeneratedApiMetadata corex_generated_apis[] = {
    {"cudaDeviceSynchronize", 4u, CRX_CAP_STREAM_EVENT, "semantic_rpc", 0u, 0u, "corex_backend_context_sync", corex_generated_cudaDeviceSynchronize_request_fields, 0u, corex_generated_cudaDeviceSynchronize_response_fields, 0u},
    {"cudaStreamQuery", 14u, CRX_CAP_STREAM_EVENT, "object_query", 8u, 4u, "corex_backend_stream_query", corex_generated_cudaStreamQuery_request_fields, 1u, corex_generated_cudaStreamQuery_response_fields, 1u},
    {"cudaEventQuery", 19u, CRX_CAP_STREAM_EVENT, "object_query", 8u, 4u, "corex_backend_event_query", corex_generated_cudaEventQuery_request_fields, 1u, corex_generated_cudaEventQuery_response_fields, 1u},
    {"cudaDeviceGetAttribute", 39u, CRX_CAP_DEVICE_INFO, "scalar_query", 8u, 4u, "corex_backend_device_attribute", corex_generated_cudaDeviceGetAttribute_request_fields, 2u, corex_generated_cudaDeviceGetAttribute_response_fields, 1u},
    {"cudaGetDeviceFlags", 40u, CRX_CAP_DEVICE_INFO, "scalar_query", 0u, 4u, "corex_backend_context_get_flags", corex_generated_cudaGetDeviceFlags_request_fields, 0u, corex_generated_cudaGetDeviceFlags_response_fields, 1u},
    {"cudaDeviceGetStreamPriorityRange", 41u, CRX_CAP_STREAM_EVENT, "scalar_query", 0u, 8u, "corex_backend_stream_priority_range", corex_generated_cudaDeviceGetStreamPriorityRange_request_fields, 0u, corex_generated_cudaDeviceGetStreamPriorityRange_response_fields, 2u},
    {"cudaDeviceGetLimit", 42u, CRX_CAP_DEVICE_INFO, "scalar_query", 4u, 8u, "corex_backend_context_get_limit", corex_generated_cudaDeviceGetLimit_request_fields, 1u, corex_generated_cudaDeviceGetLimit_response_fields, 1u},
    {"cudaDeviceGetCacheConfig", 43u, CRX_CAP_DEVICE_INFO, "scalar_query", 0u, 4u, "corex_backend_context_get_cache_config", corex_generated_cudaDeviceGetCacheConfig_request_fields, 0u, corex_generated_cudaDeviceGetCacheConfig_response_fields, 1u},
    {"cudaDeviceGetSharedMemConfig", 44u, CRX_CAP_DEVICE_INFO, "scalar_query", 0u, 4u, "corex_backend_context_get_shared_mem_config", corex_generated_cudaDeviceGetSharedMemConfig_request_fields, 0u, corex_generated_cudaDeviceGetSharedMemConfig_response_fields, 1u},
    {"cudaFuncSetAttribute", 45u, CRX_CAP_MODULE_KERNEL, "semantic_rpc", 16u, 0u, "corex_backend_function_set_attribute", corex_generated_cudaFuncSetAttribute_request_fields, 3u, corex_generated_cudaFuncSetAttribute_response_fields, 0u},
    {"cudaFuncSetCacheConfig", 46u, CRX_CAP_MODULE_KERNEL, "semantic_rpc", 12u, 0u, "corex_backend_function_set_cache_config", corex_generated_cudaFuncSetCacheConfig_request_fields, 2u, corex_generated_cudaFuncSetCacheConfig_response_fields, 0u},
};
#define COREX_GENERATED_API_COUNT 11u
static inline int corex_generated_validate_payload(uint32_t opcode, size_t length)
{
    for (size_t i = 0; i < COREX_GENERATED_API_COUNT; ++i)
        if (corex_generated_apis[i].opcode == opcode)
            return length == corex_generated_apis[i].request_bytes ? 0 : -1;
    return -1; /* unknown schema entries never guess */
}
static inline int corex_generated_validate_response(uint32_t opcode, size_t length)
{
    for (size_t i = 0; i < COREX_GENERATED_API_COUNT; ++i)
        if (corex_generated_apis[i].opcode == opcode)
            return length == corex_generated_apis[i].response_bytes ? 0 : -1;
    return -1;
}
/* Registry metadata is in corex_generated_apis[]. */
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaDeviceSynchronizeRequest;
static inline int corex_generated_encode_cudaDeviceSynchronize_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceSynchronizeRequest *value)
{
    (void)output; (void)capacity;
    if (!value) return -1;
    size_t position = 0;
    return position == 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceSynchronize_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceSynchronizeRequest *value)
{
    (void)input;
    if (!value || length != 0u) return -1;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaDeviceSynchronizeResponse;
static inline int corex_generated_encode_cudaDeviceSynchronize_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceSynchronizeResponse *value)
{
    (void)output; (void)capacity;
    if (!value) return -1;
    size_t position = 0;
    return position == 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceSynchronize_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceSynchronizeResponse *value)
{
    (void)input;
    if (!value || length != 0u) return -1;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    uint64_t stream;
} CorexGeneratedcudaStreamQueryRequest;
static inline int corex_generated_encode_cudaStreamQuery_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaStreamQueryRequest *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 8u) return -1;
    size_t position = 0;
    corex_protocol_write_u64(output, &position, (uint64_t)value->stream);
    return position == 8u ? 0 : -1;
}
static inline int corex_generated_decode_cudaStreamQuery_request(const unsigned char *input, size_t length, CorexGeneratedcudaStreamQueryRequest *value)
{
    (void)input;
    if (!input || !value || length != 8u) return -1;
    size_t position = 0;
    uint64_t stream_wire; if (corex_protocol_take_u64(input, length, &position, &stream_wire) != 0) return -1; value->stream = (uint64_t)stream_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint32_t state;
} CorexGeneratedcudaStreamQueryResponse;
static inline int corex_generated_encode_cudaStreamQuery_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaStreamQueryResponse *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->state);
    return position == 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaStreamQuery_response(const unsigned char *input, size_t length, CorexGeneratedcudaStreamQueryResponse *value)
{
    (void)input;
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t state_wire; if (corex_protocol_take_u32(input, length, &position, &state_wire) != 0) return -1; value->state = (uint32_t)state_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint64_t event;
} CorexGeneratedcudaEventQueryRequest;
static inline int corex_generated_encode_cudaEventQuery_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaEventQueryRequest *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 8u) return -1;
    size_t position = 0;
    corex_protocol_write_u64(output, &position, (uint64_t)value->event);
    return position == 8u ? 0 : -1;
}
static inline int corex_generated_decode_cudaEventQuery_request(const unsigned char *input, size_t length, CorexGeneratedcudaEventQueryRequest *value)
{
    (void)input;
    if (!input || !value || length != 8u) return -1;
    size_t position = 0;
    uint64_t event_wire; if (corex_protocol_take_u64(input, length, &position, &event_wire) != 0) return -1; value->event = (uint64_t)event_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint32_t state;
} CorexGeneratedcudaEventQueryResponse;
static inline int corex_generated_encode_cudaEventQuery_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaEventQueryResponse *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->state);
    return position == 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaEventQuery_response(const unsigned char *input, size_t length, CorexGeneratedcudaEventQueryResponse *value)
{
    (void)input;
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t state_wire; if (corex_protocol_take_u32(input, length, &position, &state_wire) != 0) return -1; value->state = (uint32_t)state_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    int32_t attribute;
    int32_t device;
} CorexGeneratedcudaDeviceGetAttributeRequest;
static inline int corex_generated_encode_cudaDeviceGetAttribute_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceGetAttributeRequest *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 8u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->attribute);
    corex_protocol_write_u32(output, &position, (uint32_t)value->device);
    return position == 8u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetAttribute_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetAttributeRequest *value)
{
    (void)input;
    if (!input || !value || length != 8u) return -1;
    size_t position = 0;
    uint32_t attribute_wire; if (corex_protocol_take_u32(input, length, &position, &attribute_wire) != 0) return -1; value->attribute = (int32_t)attribute_wire;
    uint32_t device_wire; if (corex_protocol_take_u32(input, length, &position, &device_wire) != 0) return -1; value->device = (int32_t)device_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    int32_t value;
} CorexGeneratedcudaDeviceGetAttributeResponse;
static inline int corex_generated_encode_cudaDeviceGetAttribute_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceGetAttributeResponse *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->value);
    return position == 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetAttribute_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetAttributeResponse *value)
{
    (void)input;
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t value_wire; if (corex_protocol_take_u32(input, length, &position, &value_wire) != 0) return -1; value->value = (int32_t)value_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaGetDeviceFlagsRequest;
static inline int corex_generated_encode_cudaGetDeviceFlags_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaGetDeviceFlagsRequest *value)
{
    (void)output; (void)capacity;
    if (!value) return -1;
    size_t position = 0;
    return position == 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaGetDeviceFlags_request(const unsigned char *input, size_t length, CorexGeneratedcudaGetDeviceFlagsRequest *value)
{
    (void)input;
    if (!value || length != 0u) return -1;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    uint32_t flags;
} CorexGeneratedcudaGetDeviceFlagsResponse;
static inline int corex_generated_encode_cudaGetDeviceFlags_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaGetDeviceFlagsResponse *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->flags);
    return position == 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaGetDeviceFlags_response(const unsigned char *input, size_t length, CorexGeneratedcudaGetDeviceFlagsResponse *value)
{
    (void)input;
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t flags_wire; if (corex_protocol_take_u32(input, length, &position, &flags_wire) != 0) return -1; value->flags = (uint32_t)flags_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaDeviceGetStreamPriorityRangeRequest;
static inline int corex_generated_encode_cudaDeviceGetStreamPriorityRange_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceGetStreamPriorityRangeRequest *value)
{
    (void)output; (void)capacity;
    if (!value) return -1;
    size_t position = 0;
    return position == 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetStreamPriorityRange_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetStreamPriorityRangeRequest *value)
{
    (void)input;
    if (!value || length != 0u) return -1;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    int32_t least_priority;
    int32_t greatest_priority;
} CorexGeneratedcudaDeviceGetStreamPriorityRangeResponse;
static inline int corex_generated_encode_cudaDeviceGetStreamPriorityRange_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceGetStreamPriorityRangeResponse *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 8u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->least_priority);
    corex_protocol_write_u32(output, &position, (uint32_t)value->greatest_priority);
    return position == 8u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetStreamPriorityRange_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetStreamPriorityRangeResponse *value)
{
    (void)input;
    if (!input || !value || length != 8u) return -1;
    size_t position = 0;
    uint32_t least_priority_wire; if (corex_protocol_take_u32(input, length, &position, &least_priority_wire) != 0) return -1; value->least_priority = (int32_t)least_priority_wire;
    uint32_t greatest_priority_wire; if (corex_protocol_take_u32(input, length, &position, &greatest_priority_wire) != 0) return -1; value->greatest_priority = (int32_t)greatest_priority_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    int32_t limit;
} CorexGeneratedcudaDeviceGetLimitRequest;
static inline int corex_generated_encode_cudaDeviceGetLimit_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceGetLimitRequest *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->limit);
    return position == 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetLimit_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetLimitRequest *value)
{
    (void)input;
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t limit_wire; if (corex_protocol_take_u32(input, length, &position, &limit_wire) != 0) return -1; value->limit = (int32_t)limit_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint64_t value;
} CorexGeneratedcudaDeviceGetLimitResponse;
static inline int corex_generated_encode_cudaDeviceGetLimit_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceGetLimitResponse *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 8u) return -1;
    size_t position = 0;
    corex_protocol_write_u64(output, &position, (uint64_t)value->value);
    return position == 8u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetLimit_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetLimitResponse *value)
{
    (void)input;
    if (!input || !value || length != 8u) return -1;
    size_t position = 0;
    uint64_t value_wire; if (corex_protocol_take_u64(input, length, &position, &value_wire) != 0) return -1; value->value = (uint64_t)value_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaDeviceGetCacheConfigRequest;
static inline int corex_generated_encode_cudaDeviceGetCacheConfig_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceGetCacheConfigRequest *value)
{
    (void)output; (void)capacity;
    if (!value) return -1;
    size_t position = 0;
    return position == 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetCacheConfig_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetCacheConfigRequest *value)
{
    (void)input;
    if (!value || length != 0u) return -1;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    int32_t config;
} CorexGeneratedcudaDeviceGetCacheConfigResponse;
static inline int corex_generated_encode_cudaDeviceGetCacheConfig_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceGetCacheConfigResponse *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->config);
    return position == 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetCacheConfig_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetCacheConfigResponse *value)
{
    (void)input;
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t config_wire; if (corex_protocol_take_u32(input, length, &position, &config_wire) != 0) return -1; value->config = (int32_t)config_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaDeviceGetSharedMemConfigRequest;
static inline int corex_generated_encode_cudaDeviceGetSharedMemConfig_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceGetSharedMemConfigRequest *value)
{
    (void)output; (void)capacity;
    if (!value) return -1;
    size_t position = 0;
    return position == 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetSharedMemConfig_request(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetSharedMemConfigRequest *value)
{
    (void)input;
    if (!value || length != 0u) return -1;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    int32_t config;
} CorexGeneratedcudaDeviceGetSharedMemConfigResponse;
static inline int corex_generated_encode_cudaDeviceGetSharedMemConfig_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaDeviceGetSharedMemConfigResponse *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 4u) return -1;
    size_t position = 0;
    corex_protocol_write_u32(output, &position, (uint32_t)value->config);
    return position == 4u ? 0 : -1;
}
static inline int corex_generated_decode_cudaDeviceGetSharedMemConfig_response(const unsigned char *input, size_t length, CorexGeneratedcudaDeviceGetSharedMemConfigResponse *value)
{
    (void)input;
    if (!input || !value || length != 4u) return -1;
    size_t position = 0;
    uint32_t config_wire; if (corex_protocol_take_u32(input, length, &position, &config_wire) != 0) return -1; value->config = (int32_t)config_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint64_t kernel;
    int32_t attribute;
    int32_t value;
} CorexGeneratedcudaFuncSetAttributeRequest;
static inline int corex_generated_encode_cudaFuncSetAttribute_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaFuncSetAttributeRequest *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 16u) return -1;
    size_t position = 0;
    corex_protocol_write_u64(output, &position, (uint64_t)value->kernel);
    corex_protocol_write_u32(output, &position, (uint32_t)value->attribute);
    corex_protocol_write_u32(output, &position, (uint32_t)value->value);
    return position == 16u ? 0 : -1;
}
static inline int corex_generated_decode_cudaFuncSetAttribute_request(const unsigned char *input, size_t length, CorexGeneratedcudaFuncSetAttributeRequest *value)
{
    (void)input;
    if (!input || !value || length != 16u) return -1;
    size_t position = 0;
    uint64_t kernel_wire; if (corex_protocol_take_u64(input, length, &position, &kernel_wire) != 0) return -1; value->kernel = (uint64_t)kernel_wire;
    uint32_t attribute_wire; if (corex_protocol_take_u32(input, length, &position, &attribute_wire) != 0) return -1; value->attribute = (int32_t)attribute_wire;
    uint32_t value_wire; if (corex_protocol_take_u32(input, length, &position, &value_wire) != 0) return -1; value->value = (int32_t)value_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaFuncSetAttributeResponse;
static inline int corex_generated_encode_cudaFuncSetAttribute_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaFuncSetAttributeResponse *value)
{
    (void)output; (void)capacity;
    if (!value) return -1;
    size_t position = 0;
    return position == 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaFuncSetAttribute_response(const unsigned char *input, size_t length, CorexGeneratedcudaFuncSetAttributeResponse *value)
{
    (void)input;
    if (!value || length != 0u) return -1;
    size_t position = 0;
    return position == length ? 0 : -1;
}
typedef struct {
    uint64_t kernel;
    int32_t config;
} CorexGeneratedcudaFuncSetCacheConfigRequest;
static inline int corex_generated_encode_cudaFuncSetCacheConfig_request(unsigned char *output, size_t capacity, const CorexGeneratedcudaFuncSetCacheConfigRequest *value)
{
    (void)output; (void)capacity;
    if (!output || !value || capacity < 12u) return -1;
    size_t position = 0;
    corex_protocol_write_u64(output, &position, (uint64_t)value->kernel);
    corex_protocol_write_u32(output, &position, (uint32_t)value->config);
    return position == 12u ? 0 : -1;
}
static inline int corex_generated_decode_cudaFuncSetCacheConfig_request(const unsigned char *input, size_t length, CorexGeneratedcudaFuncSetCacheConfigRequest *value)
{
    (void)input;
    if (!input || !value || length != 12u) return -1;
    size_t position = 0;
    uint64_t kernel_wire; if (corex_protocol_take_u64(input, length, &position, &kernel_wire) != 0) return -1; value->kernel = (uint64_t)kernel_wire;
    uint32_t config_wire; if (corex_protocol_take_u32(input, length, &position, &config_wire) != 0) return -1; value->config = (int32_t)config_wire;
    return position == length ? 0 : -1;
}
typedef struct {
    uint8_t _empty;
} CorexGeneratedcudaFuncSetCacheConfigResponse;
static inline int corex_generated_encode_cudaFuncSetCacheConfig_response(unsigned char *output, size_t capacity, const CorexGeneratedcudaFuncSetCacheConfigResponse *value)
{
    (void)output; (void)capacity;
    if (!value) return -1;
    size_t position = 0;
    return position == 0u ? 0 : -1;
}
static inline int corex_generated_decode_cudaFuncSetCacheConfig_response(const unsigned char *input, size_t length, CorexGeneratedcudaFuncSetCacheConfigResponse *value)
{
    (void)input;
    if (!value || length != 0u) return -1;
    size_t position = 0;
    return position == length ? 0 : -1;
}
#endif
