/* Generated by scripts/generate-api-schema.py; DO NOT EDIT. */
#include "corex_api_schema.h"
#include <stdio.h>
int main(void) {
    if (COREX_GENERATED_API_COUNT != 11u) return 1;
    if (corex_generated_validate_payload(4u, 0u) != 0) return 1;
    if (corex_generated_validate_response(4u, 0u) != 0) return 1;
    (void)corex_generated_cudaDeviceSynchronize_request_fields;
    if (corex_generated_validate_payload(14u, 8u) != 0) return 1;
    if (corex_generated_validate_response(14u, 4u) != 0) return 1;
    (void)corex_generated_cudaStreamQuery_request_fields;
    if (corex_generated_validate_payload(19u, 8u) != 0) return 1;
    if (corex_generated_validate_response(19u, 4u) != 0) return 1;
    (void)corex_generated_cudaEventQuery_request_fields;
    if (corex_generated_validate_payload(39u, 8u) != 0) return 1;
    if (corex_generated_validate_response(39u, 4u) != 0) return 1;
    (void)corex_generated_cudaDeviceGetAttribute_request_fields;
    if (corex_generated_validate_payload(40u, 0u) != 0) return 1;
    if (corex_generated_validate_response(40u, 4u) != 0) return 1;
    (void)corex_generated_cudaGetDeviceFlags_request_fields;
    if (corex_generated_validate_payload(41u, 0u) != 0) return 1;
    if (corex_generated_validate_response(41u, 8u) != 0) return 1;
    (void)corex_generated_cudaDeviceGetStreamPriorityRange_request_fields;
    if (corex_generated_validate_payload(42u, 4u) != 0) return 1;
    if (corex_generated_validate_response(42u, 8u) != 0) return 1;
    (void)corex_generated_cudaDeviceGetLimit_request_fields;
    if (corex_generated_validate_payload(43u, 0u) != 0) return 1;
    if (corex_generated_validate_response(43u, 4u) != 0) return 1;
    (void)corex_generated_cudaDeviceGetCacheConfig_request_fields;
    if (corex_generated_validate_payload(44u, 0u) != 0) return 1;
    if (corex_generated_validate_response(44u, 4u) != 0) return 1;
    (void)corex_generated_cudaDeviceGetSharedMemConfig_request_fields;
    if (corex_generated_validate_payload(45u, 16u) != 0) return 1;
    if (corex_generated_validate_response(45u, 0u) != 0) return 1;
    (void)corex_generated_cudaFuncSetAttribute_request_fields;
    if (corex_generated_validate_payload(46u, 12u) != 0) return 1;
    if (corex_generated_validate_response(46u, 0u) != 0) return 1;
    (void)corex_generated_cudaFuncSetCacheConfig_request_fields;
    if (corex_generated_validate_payload(999u, 0) == 0 ||
        corex_generated_validate_response(999u, 0) == 0 ||
        corex_generated_validate_payload(OP_STREAM_QUERY, 7) == 0) return 1;
    puts("M3_S6_GENERATED_SCHEMA_TEST=PASS");
    return 0;
}
