#!/usr/bin/env python3
"""Generate small, reviewable metadata/adapters from the M2-S5 schema."""
import argparse
import json
from pathlib import Path

OPCODES = {"OP_SYNC", "OP_STREAM_QUERY", "OP_EVENT_QUERY"}
CAPABILITIES = {"CRX_CAP_STREAM_EVENT"}
TYPES = {"u64": 8}
DIRECTIONS = {"in"}
OBJECTS = {"stream_id", "event_id"}


def fail(message):
    raise SystemExit(f"schema error: {message}")


def load(path):
    data = json.loads(path.read_text())
    if data.get("schema_version") != 1 or not isinstance(data.get("apis"), list):
        fail("schema_version=1 and apis[] are required")
    seen = set()
    for api in data["apis"]:
        required = {"name", "opcode", "capability_id", "wire_payload_bytes", "parameters"}
        if set(api) != required:
            fail(f"{api.get('name', '<unnamed>')}: exact API fields required")
        if api["opcode"] not in OPCODES or api["capability_id"] not in CAPABILITIES:
            fail(f"{api['name']}: unsupported opcode/capability; add an explicit generator rule")
        if api["name"] in seen:
            fail(f"duplicate API {api['name']}")
        seen.add(api["name"])
        if not isinstance(api["parameters"], list):
            fail(f"{api['name']}: parameters must be a list")
        total = 0
        for parameter in api["parameters"]:
            required_parameter = {"name", "direction", "type", "object", "max_bytes"}
            if set(parameter) != required_parameter:
                fail(f"{api['name']}: exact parameter fields required")
            if parameter["direction"] not in DIRECTIONS or parameter["type"] not in TYPES:
                fail(f"{api['name']}: unsupported parameter type/direction")
            if parameter["object"] not in OBJECTS or parameter["max_bytes"] != TYPES[parameter["type"]]:
                fail(f"{api['name']}: object reference/limit is not proven")
            total += TYPES[parameter["type"]]
        if api["wire_payload_bytes"] != total:
            fail(f"{api['name']}: wire_payload_bytes does not match parameters")
    return data


def render(data):
    apis = data["apis"]
    lines = [
        "/* Generated by scripts/generate-api-schema.py; do not edit. */",
        "#ifndef COREX_GENERATED_API_SCHEMA_H",
        "#define COREX_GENERATED_API_SCHEMA_H",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "#include \"corex_protocol.h\"",
        "typedef struct { const char *name; uint32_t opcode; uint32_t capability_id; uint32_t payload_bytes; } CorexGeneratedApiMetadata;",
        "static const CorexGeneratedApiMetadata corex_generated_apis[] = {",
    ]
    for api in apis:
        lines.append(f"    {{\"{api['name']}\", {api['opcode']}, {api['capability_id']}, {api['wire_payload_bytes']}}},")
    lines += [
        "};",
        f"#define COREX_GENERATED_API_COUNT {len(apis)}u",
        "static inline int corex_generated_validate_payload(uint32_t opcode, size_t length)",
        "{",
        "    for (size_t i = 0; i < COREX_GENERATED_API_COUNT; ++i)",
        "        if (corex_generated_apis[i].opcode == opcode)",
        "            return length == corex_generated_apis[i].payload_bytes ? 0 : -1;",
        "    return -1; /* unknown schema entries never guess */",
        "}",
        "#define COREX_GENERATED_HANDLER_METADATA(X) \\",
    ]
    for index, api in enumerate(apis):
        suffix = " " + "\\" if index + 1 < len(apis) else ""
        lines.append(f"    X({api['opcode']}, {api['capability_id']}){suffix}")
    lines += ["#endif", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--test-output", type=Path, required=True)
    args = parser.parse_args()
    data = load(args.schema)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.test_output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(data))
    args.test_output.write_text("""/* Generated test skeleton: positive and bounded-negative schema checks. */
#include \"corex_api_schema.h\"
#include <stdio.h>
int main(void) {
    if (COREX_GENERATED_API_COUNT != 3u ||
        corex_generated_validate_payload(OP_SYNC, 0) != 0 ||
        corex_generated_validate_payload(OP_STREAM_QUERY, 8) != 0 ||
        corex_generated_validate_payload(OP_EVENT_QUERY, 7) == 0 ||
        corex_generated_validate_payload(999u, 0) == 0)
        return 1;
    puts(\"M2_S5_GENERATED_SCHEMA_TEST=PASS\");
    return 0;
}
""")


if __name__ == "__main__":
    main()
